# Generated by Django 3.1.5 on 2021-02-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP_Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.TextField()),
                ('ICE', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now=True)),
                ('Number_Of_Use', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Created_Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atestation_Number', models.IntegerField(unique=True)),
                ('client_address', models.TextField()),
                ('Date', models.DateField()),
                ('Client_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.app_clients')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Created_Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_number', models.IntegerField(unique=True)),
                ('Client_Name', models.TextField()),
                ('ICE', models.CharField(max_length=255)),
                ('Date', models.DateField(max_length=255)),
                ('Place', models.CharField(max_length=255)),
                ('isPaid', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=5)),
                ('Paiment_Mathod', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Cart', 'Cart')], default='aucun', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PU', models.IntegerField()),
                ('DESIGNATION', models.TextField()),
                ('Number_Of_Use', models.IntegerField(default=None, null=True)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_ICE', models.CharField(default='00000000000000', max_length=255)),
                ('Company_TVATAUX', models.IntegerField(default=20)),
                ('Company_Place', models.CharField(default='Tanger', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APP_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpermission', models.CharField(choices=[('Admin', 'Admin'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=30)),
                ('ProfileFolderPath', models.TextField(editable=False)),
                ('account_status', models.CharField(choices=[('Suspendu', 'Suspendu'), ('Active', 'Active')], default='Suspendu', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=255)),
                ('what_detail', models.TextField()),
                ('What_DateTime', models.DateTimeField(auto_now=True, max_length=255)),
                ('Who', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APP_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_detail', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now=True, max_length=255)),
                ('CreatedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Facture_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qs', models.IntegerField(default=0)),
                ('DESIGNATION', models.TextField(default=None)),
                ('PU', models.IntegerField(default=0)),
                ('PT', models.BigIntegerField(default=0)),
                ('BelongToFacture', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.app_created_facture')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Facture_File_Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacturePath', models.TextField(max_length=255)),
                ('FileSize', models.CharField(max_length=255, null=True)),
                ('BelongTo', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.app_created_facture')),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.app_user')),
            ],
        ),
        migrations.AddField(
            model_name='app_created_facture',
            name='CreatedBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.app_user'),
        ),
        migrations.CreateModel(
            name='APP_Created_Attestation_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESIGNATION', models.TextField()),
                ('MARQUE', models.TextField()),
                ('MODEL', models.TextField()),
                ('NEMURO_DE_SERIE', models.TextField()),
                ('N_INTERVENTION', models.TextField()),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Created_Attestation_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BelongToAttestation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.app_created_attestation')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.app_created_attestation_products')),
            ],
        ),
        migrations.AddField(
            model_name='app_created_attestation',
            name='CreatedBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.app_user'),
        ),
    ]
