# Generated by Django 4.1.1 on 2022-09-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP_Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.TextField()),
                ('ICE', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now=True)),
                ('Number_Of_Use', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Created_Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('Date', models.DateField(max_length=255)),
                ('HT', models.FloatField()),
                ('Client', models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='efacture.app_clients')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Created_Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('Date', models.DateField(max_length=255)),
                ('HT', models.FloatField()),
                ('TVA', models.FloatField()),
                ('TTC', models.FloatField()),
                ('TTCorHT', models.CharField(choices=[('HT', 'HT'), ('TTC', 'TTC')], default='TTC', max_length=3)),
                ('isPaid', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=5)),
                ('Avance', models.FloatField(default=0)),
                ('Paiment_Mathod', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Letter', 'Letter'), ('Virement', 'Virement')], default='aucun', max_length=255)),
                ('ConvertedFromBLs', models.TextField(default=False, editable=False, null=True)),
                ('Client', models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='efacture.app_clients')),
                ('ConvertedFromDevis', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='efacture.app_created_devis')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PU', models.FloatField()),
                ('DESIGNATION', models.TextField()),
                ('Number_Of_Use', models.IntegerField(default=None, null=True)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_ICE', models.CharField(default='00000000000000', max_length=255)),
                ('Company_TVATAUX', models.FloatField(default=20)),
                ('Company_Place', models.CharField(default='earth', max_length=255)),
                ('APP_lang', models.CharField(choices=[('fr', 'fr'), ('ar', 'ar'), ('en', 'en')], default='fr', max_length=3)),
                ('Invoice_Color', models.CharField(default='#000000', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APP_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpermission', models.CharField(choices=[('Admin', 'Admin'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=30)),
                ('ProfileFolderPath', models.TextField(editable=False)),
                ('account_status', models.CharField(choices=[('Suspendu', 'Suspendu'), ('Active', 'Active')], default='Suspendu', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='APP_Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=255)),
                ('what_detail', models.TextField()),
                ('What_DateTime', models.DateTimeField(auto_now=True, max_length=255)),
                ('Who', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APP_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_detail', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now=True, max_length=255)),
                ('CreatedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='efacture.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Facture_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qs', models.FloatField(default=0)),
                ('DESIGNATION', models.TextField(default=None)),
                ('PU', models.FloatField(default=0)),
                ('PT', models.FloatField(default=0)),
                ('Date', models.DateField(auto_now=True)),
                ('BelongToFacture', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='efacture.app_created_facture')),
            ],
        ),
        migrations.CreateModel(
            name='APP_Devis_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qs', models.FloatField(default=0)),
                ('DESIGNATION', models.TextField(default=None)),
                ('PU', models.FloatField(default=0)),
                ('PT', models.FloatField(default=0)),
                ('BelongToDevis', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='efacture.app_created_devis')),
            ],
        ),
        migrations.AddField(
            model_name='app_created_facture',
            name='CreatedBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='efacture.app_user'),
        ),
        migrations.AddField(
            model_name='app_created_devis',
            name='CreatedBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='efacture.app_user'),
        ),
        migrations.CreateModel(
            name='APP_Created_BL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('Date', models.DateField(max_length=255)),
                ('HT', models.FloatField()),
                ('Client', models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='efacture.app_clients')),
                ('CreatedBy', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='efacture.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='APP_BL_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qs', models.FloatField(default=0)),
                ('DESIGNATION', models.TextField(default=None)),
                ('PU', models.FloatField(default=0)),
                ('PT', models.FloatField(default=0)),
                ('Date', models.DateField(auto_now=True)),
                ('BelongToBL', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='efacture.app_created_bl')),
            ],
        ),
    ]
